version: '3.8'

services:
  base:
    build:
      context: .
      dockerfile: Dockerfile
    image: tomok-base:latest
  api:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    depends_on:
      - base
    volumes:
      - ../tomok_assets/ruleunits:/app/api_server/ruleunits
    ports:
      - "51515:51515"
    environment:
      - PORT=51515