name: tomok_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.4
  - nodejs=20.9.0
  - gcc_linux-64=9.4.0
  - pip
  - pip:
      - psycopg2-binary
      - .
      - -r requirements.txt
